export interface Database {
  public: {
    Tables: {
      quotes: {
        Row: {
          id: string;
          user_id: string;
          quote_number: string;
          cargo_type: string;
          shipment_value: number;
          origin: any;
          destination: any;
          start_date: string;
          end_date: string;
          transportation_mode: string;
          selected_coverage: 'standard' | 'premium' | 'enterprise';
          calculated_premium: number;
          deductible: number;
          status: 'draft' | 'submitted' | 'under_review' | 'approved' | 'rejected' | 'expired';
          payment_status: 'pending' | 'paid' | 'failed';
          quote_expires_at: string;
          created_at: string;
          updated_at: string;
          approved_at?: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          quote_number: string;
          cargo_type: string;
          shipment_value: number;
          origin?: any;
          destination?: any;
          start_date: string;
          end_date: string;
          transportation_mode: string;
          selected_coverage?: 'standard' | 'premium' | 'enterprise';
          calculated_premium?: number;
          deductible?: number;
          status?: 'draft' | 'submitted' | 'under_review' | 'approved' | 'rejected' | 'expired';
          payment_status?: 'pending' | 'paid' | 'failed';
          quote_expires_at?: string;
          created_at?: string;
          updated_at?: string;
          approved_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          quote_number?: string;
          cargo_type?: string;
          shipment_value?: number;
          origin?: any;
          destination?: any;
          start_date?: string;
          end_date?: string;
          transportation_mode?: string;
          selected_coverage?: 'standard' | 'premium' | 'enterprise';
          calculated_premium?: number;
          deductible?: number;
          status?: 'draft' | 'submitted' | 'under_review' | 'approved' | 'rejected' | 'expired';
          payment_status?: 'pending' | 'paid' | 'failed';
          quote_expires_at?: string;
          created_at?: string;
          updated_at?: string;
          approved_at?: string;
        };
      };
      payments: {
        Row: {
          id: string;
          quote_id: string;
          policy_id?: string;
          user_id: string;
          amount: number;
          currency: string;
          payment_method: 'credit_card' | 'bank_transfer' | 'check' | 'cash';
          payment_status: 'pending' | 'processing' | 'completed' | 'failed' | 'refunded';
          card_last_four?: string;
          card_brand?: string;
          bank_name?: string;
          bank_account_last_four?: string;
          transaction_id?: string;
          gateway?: string;
          created_at: string;
          updated_at: string;
          processed_at?: string;
          completed_at?: string;
        };
        Insert: {
          id?: string;
          quote_id: string;
          policy_id?: string;
          user_id: string;
          amount: number;
          currency?: string;
          payment_method: 'credit_card' | 'bank_transfer' | 'check' | 'cash';
          payment_status?: 'pending' | 'processing' | 'completed' | 'failed' | 'refunded';
          card_last_four?: string;
          card_brand?: string;
          bank_name?: string;
          bank_account_last_four?: string;
          transaction_id?: string;
          gateway?: string;
          created_at?: string;
          updated_at?: string;
          processed_at?: string;
          completed_at?: string;
        };
        Update: {
          id?: string;
          quote_id?: string;
          policy_id?: string;
          user_id?: string;
          amount?: number;
          currency?: string;
          payment_method?: 'credit_card' | 'bank_transfer' | 'check' | 'cash';
          payment_status?: 'pending' | 'processing' | 'completed' | 'failed' | 'refunded';
          card_last_four?: string;
          card_brand?: string;
          bank_name?: string;
          bank_account_last_four?: string;
          transaction_id?: string;
          gateway?: string;
          created_at?: string;
          updated_at?: string;
          processed_at?: string;
          completed_at?: string;
        };
      };
      policies: {
        Row: {
          id: string;
          quote_id: string;
          user_id: string;
          policy_number: string;
          status: 'draft' | 'active' | 'expired' | 'cancelled';
          coverage_type: 'standard' | 'premium' | 'enterprise';
          premium_amount: number;
          deductible: number;
          start_date: string;
          end_date: string;
          created_at: string;
          updated_at: string;
          activated_at?: string;
          cancelled_at?: string;
        };
        Insert: {
          id?: string;
          quote_id: string;
          user_id: string;
          policy_number: string;
          status?: 'draft' | 'active' | 'expired' | 'cancelled';
          coverage_type: 'standard' | 'premium' | 'enterprise';
          premium_amount: number;
          deductible: number;
          start_date: string;
          end_date: string;
          created_at?: string;
          updated_at?: string;
          activated_at?: string;
          cancelled_at?: string;
        };
        Update: {
          id?: string;
          quote_id?: string;
          user_id?: string;
          policy_number?: string;
          status?: 'draft' | 'active' | 'expired' | 'cancelled';
          coverage_type?: 'standard' | 'premium' | 'enterprise';
          premium_amount?: number;
          deductible?: number;
          start_date?: string;
          end_date?: string;
          created_at?: string;
          updated_at?: string;
          activated_at?: string;
          cancelled_at?: string;
        };
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
  };
}